import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { ReactQueryProvider } from "@/common/lib/react-query";
import { Header, Footer } from "@/components";

import "@/common/assets/css/bootstrap.min.css";
// import "@/common/assets/css/owl.carousel.min.css";
// import "@/common/assets/css/ticker-style.css";
import "@/common/assets/css/flaticon.css";
import "@/common/assets/css/slicknav.css";
import "@/common/assets/css/animate.min.css";
import "@/common/assets/css/magnific-popup.css";
import "@/common/assets/css/fontawesome-all.min.css";
import "@/common/assets/css/themify-icons.css";
import "@/common/assets/css/slick.css";
import "@/common/assets/css/nice-select.css";
import "@/common/assets/css/style.css";
import "quill/dist/quill.snow.css";
import "swiper/css";

import "./globals.css";

const nunito = Nunito({
  weight: ["400", "700"],
  subsets: ["latin", "cyrillic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ReactQueryProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
