import type { Metadata } from "next";
import localFont from "next/font/local";

import { ReactQueryProvider } from "@/common/lib/react-query";
import { Header, Footer } from "@/components";

import "@/common/assets/css/bootstrap.min.css";
// import "@/common/assets/css/owl.carousel.min.css";
// import "@/common/assets/css/ticker-style.css";
import "@/common/assets/css/flaticon.css";
import "@/common/assets/css/slicknav.css";
import "@/common/assets/css/animate.min.css";
import "@/common/assets/css/magnific-popup.css";
import "@/common/assets/css/fontawesome-all.min.css";
import "@/common/assets/css/themify-icons.css";
import "@/common/assets/css/slick.css";
import "@/common/assets/css/nice-select.css";
import "@/common/assets/css/style.css";
import "swiper/css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
