import "@/common/assets/css/bootstrap.min.css";
import "@/common/assets/css/flaticon.css";
import "@/common/assets/css/slicknav.css";
import "@/common/assets/css/animate.min.css";
import "@/common/assets/css/magnific-popup.css";
import "@/common/assets/css/fontawesome-all.min.css";
import "@/common/assets/css/themify-icons.css";
import "@/common/assets/css/slick.css";
import "@/common/assets/css/nice-select.css";
import "@/common/assets/css/style.css";
import "quill/dist/quill.snow.css";
import "swiper/css";
import "./globals.css";

import { Footer, Header } from "@/components";

import type { Metadata } from "next";
import { ReactQueryProvider } from "@/common/lib/react-query";
import localFont from "next/font/local";

const nunito = localFont({
  src: [
    {
      path: "./fonts/Nunito/Nunito-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Nunito/Nunito-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Nunito/Nunito-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Nunito/Nunito-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

// import "@/common/assets/css/owl.carousel.min.css";
// import "@/common/assets/css/ticker-style.css";

// const nunito = Nunito({
//   weight: ["400", "700"],
//   subsets: ["latin", "cyrillic"],
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ReactQueryProvider>
          <Header />
          <main className="flex-1 overflow-y-auto">
            {children}
            <Footer />
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
